config/routes.rb
GithubSocialAuth::Application.routes.draw do
  get "users/show"
  get "pages/home"
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'sessions#failure'
  match 'sign_out' => 'sessions#destroy'
  root :to => "pages#home"
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :provider, :uid  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name
  has_many :authentications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  
  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth["provider"],omniauth["uid"])
    if authentication
      redirect_to users_show_path
    else
      user = User.new
      user.authentications.build(:provider => omniauth["provider"], :uid => omniauth["uid"])
      user.name = omniauth["info"]["name"]
      user.email = omniauth["info"]["email"]
      user.nickname = omniauth["info"]["nickname"]
      user.save!
      redirect_to users_show_path
    end
    session[:name] = omniauth["info"]["name"]
    session[:uid] = omniauth["uid"]
    session[:provider] = omniauth["provider"]
    session[:avatar] = omniauth["info"]["image"]
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def failure
    flash[:alert] = "Authentication failure"
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    authentication = Authentication.find_by_uid(session[:uid])
    @user = User.find_by_id(authentication[:user_id])
    @repos = Github.repos.list user: @user.nickname
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Github Social Auth
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    - if session[:uid].present?
      %div
        = session[:name]
      %div
        = image_tag session[:avatar]
      %div
        = session[:provider]
      %div
        = link_to "Sign out", sign_out_path, :rel => "external"
    - else
      = link_to "Authenticate via Github", "/auth/github", :rel => "external"
    = yield

app/views/users/show.html.haml
%div
  users#show

%div= "Github user: #{@user.name}"

%ul.repos
  - @repos.each do |repo|
    %li= repo.full_name